# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZiZ0KDlEelv8bpE5crSWkRDcEwmrOiX
"""

from transformers import pipeline
import random
import spacy

nlp = spacy.load("en_core_web_sm")

class QA_Model:
    def __init__(self, model_name="bert-large-uncased-whole-word-masking-finetuned-squad"):
        self.qa_pipeline = pipeline("question-answering", model=model_name)

    def answer_question(self, context, question):
        result = self.qa_pipeline(question=question, context=context)
        return result['answer']

class CaptionChatbot:
    def __init__(self, caption):
        self.qa_model = QA_Model()
        self.caption = caption

    def extract_relevant_context(self, question):
        caption_doc = nlp(self.caption)
        question_doc = nlp(question)

        caption_entities = [ent.text for ent in caption_doc.ents]
        question_entities = [ent.text for ent in question_doc.ents]

        common_entities = set(caption_entities).intersection(set(question_entities))

        if common_entities:
            relevant_context = " ".join([ent for ent in caption_entities if ent in common_entities])
            return relevant_context if relevant_context else self.caption
        else:
            return self.caption

    def answer_from_caption(self, question):
        context = self.extract_relevant_context(question)
        answer = self.qa_model.answer_question(context, question)
        print(f"SensAI: {answer}")
        return answer

def handle_greetings():
    responses = ["Hello!", "Hey!", "Hi there!", "Howdy!", "Hey, what's up?", "Greetings!", "Good day!"]
    return random.choice(responses)

def handle_well_being():
    responses = ["I am fine, what about you? :D", "I am good!", "Doing well, thanks for asking!",
                  "I'm great, how about you?", "I'm doing fine, how are you?",
                  "All good here! How are you?"]
    return random.choice(responses)

def handle_positive_statements():
    responses = ["That's good to hear", "That's good", "That's nice!", "I'm happy to hear that!",
                  "Glad to hear!", "Awesome!", "Fantastic!", "That's wonderful!"]
    return random.choice(responses)

def handle_identity():
    responses = ["I am a chatbot here to help you. My name is SensAI :)", "I'm SensAI, your friendly chatbot :D",
                  "I'm SensAI, here to assist you! :)", "You can call me SensAI, I'm a chatbot! :D"]
    return random.choice(responses)

def handle_gratitude():
    responses = ["You're welcome!", "No problem!", "My pleasure!", "Happy to help!", "You're very welcome!",
                  "Glad I could help!", "Anytime!", "No worries!"]
    return random.choice(responses)

def handle_appearance():
    responses = ["You look fantastic in that outfit!", "Your style is always on point!", "That color really suits you!",
                  "You look great!", "You're rocking that look!", "You look awesome!", "Wow, you look amazing!",
                  "You always have the best outfits!", "You're looking sharp!", "You look fabulous!"]
    return random.choice(responses)

def handle_farewell():
    responses = ["Goodbye!", "Bye!", "See you later!", "See ya!", "Farewell!", "Take care!",
                  "Catch you later!", "Later!", "Bye Bye!"]
    return random.choice(responses)

def run_chatbot_with_caption(caption):
    chatbot = CaptionChatbot(caption)

    while True:
        question = input("User: ").lower()

        if question in ["hi", "hello", "hey", "howdy", "what's up", "greetings", "heya", "yo", "good day", "sup"]:
            print(f"SensAI: {handle_greetings()}")
            continue
        if question in ["how are you", "how do you do", "how's it going", "how are things",
                        "how have you been", "what's up", "how's everything"]:
            print(f"SensAI: {handle_well_being()}")
            continue
        if question in ["i am good", "i am fine", "fine", "good", "awesome", "great",
                        "i am awesome", "i am great", "i'm doing well", "i'm fantastic",
                        "i'm excellent"]:
            print(f"SensAI: {handle_positive_statements()}")
            continue
        if question in ["who are you", "what is your name", "what are you", "who is this",
                        "what's your name", "may i know your name", "who am i talking to",
                        "who are you again", "what should i call you"]:
            print(f"SensAI: {handle_identity()}")
            continue
        if question in ["thank you", "thanks", "thanks a lot", "thank you so much", "much appreciated",
                        "thanks a ton", "thank you very much", "many thanks", "i appreciate it"]:
            print(f"SensAI: {handle_gratitude()}")
            continue
        if question in ["how do i look", "how am i looking", "do i look good", "what do you think of my outfit",
                        "how's my outfit", "how's my look", "do i look okay", "what do you think about my look",
                        "how do i appear", "how's my style", "how do i seem", "how's my appearance",
                        "what's your opinion on my look", "how's my getup", "what do you think of my appearance",
                        "how does my outfit look", "how do i present myself", "do i look stylish",
                        "how's my fashion today", "what's your take on my outfit","describe my look","how is my outfit looking","how is my fashion sense",
                        "caption me this"]:
            print(f"SensAI: {handle_appearance()}")
            continue
        if question in ["exit", "quit", "bye", "goodbye"]:
            print(f"SensAI: {handle_farewell()}")
            break

        chatbot.answer_from_caption(question)

if __name__ == "__main__":
    caption = "A young girl is sitting by the lake, wearing a yellow dress, with birds flying in the clear blue sky and mountains in the background."
    run_chatbot_with_caption(caption)

